"""Add driver relationship to Schedule

Revision ID: 1ead2d6ba17c
Revises: e82cd176cf47
Create Date: 2024-12-05 12:32:58.891758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ead2d6ba17c'
down_revision = 'e82cd176cf47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('bus')
    op.drop_table('route')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('map_data', mysql.TEXT(), nullable=False),
    sa.Column('direction', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bus',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bus_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('schedule',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bus_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('route_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('departure_time', mysql.DATETIME(), nullable=False),
    sa.Column('is_live', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('live_until', mysql.DATETIME(), nullable=True),
    sa.Column('is_disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['bus.id'], name='schedule_ibfk_1'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name='schedule_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
