"""Added direction field to Route model.

Revision ID: 5b8b76a765e3
Revises: c30f2fe23fc8
Create Date: 2024-11-24 10:16:10.412683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8b76a765e3'
down_revision = 'c30f2fe23fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
